### ISSUE TITLE
ResizableIcon clipped

### ISSUE THREAD

**Issue by plingsi** [kirill-grouchnikov/flamingo#10]
I am using the SVG Transcoder to create a ResizableIcon from a SVG. The icons are clipped, se figure below. Is it possible to fix this?

![image](https://user-images.githubusercontent.com/10544270/29520026-ce0dcb46-867f-11e7-87cd-a8d0866b6e7e.png)
 
Regards,
Erling

**Comment by kirill-grouchnikov** [comment]
There were a few issues around int/double/float conversions in the code generated by Flamingo 5.1. Are you experiencing this issue with code generated with the latest 5.2dev bits? If so, I would need to see the original SVG for one of the images. Preferably the round light blue "i" icon, as that seems to be the simplest shape to debug.

**Comment by plingsi** [comment]
Hi,
I’m using the latest 5.2. Attatched is the original SVG.

Regards,
Erling Fagerlie

Fra: Kirill Grouchnikov [mailto:notifications@github.com]
Sendt: tirsdag 22. august 2017 04.38
Til: kirill-grouchnikov/flamingo <flamingo@noreply.github.com>
Kopi: Erling Fagerlie <erling@shiplog.no>; Author <author@noreply.github.com>
Emne: Re: [kirill-grouchnikov/flamingo] ResizableIcon clipped (#10)


There were a few issues around int/double/float conversions in the code generated by Flamingo 5.1. Are you experiencing this issue with code generated with the latest 5.2dev bits? If so, I would need to see the original SVG for one of the images. Preferably the round light blue "i" icon, as that seems to be the simplest shape to debug.

**Comment by kirill-grouchnikov** [comment]
I think this is missing the attachment.

**Comment by plingsi** [comment]
Hi,
the icon is located here:
http://85.93.234.26/shiplog/Temp/Info.svg

Regards,
Erling Fagerlie

**Comment by kirill-grouchnikov** [comment]
<img width="260" alt="info-icon" src="https://user-images.githubusercontent.com/52874/29582847-338f657a-874c-11e7-8647-f5f6c5b47ed2.png">

**Comment by kirill-grouchnikov** [comment]
`package test.svg.transcoded;

import java.awt.*;
import java.awt.geom.*;

/**
 * This class has been automatically generated using <a
 * href="https://github.com/kirill-grouchnikov/flamingo">Flamingo SVG transcoder</a>.
 */
public class Info implements
		org.pushingpixels.flamingo.api.common.icon.ResizableIcon {
	/**
	 * Paints the transcoded SVG image on the specified graphics context. You
	 * can install a custom transformation on the graphics context to scale the
	 * image.
	 * 
	 * @param g
	 *            Graphics context.
	 */
	public static void paint(Graphics2D g) {
        Shape shape = null;
        Paint paint = null;
        Stroke stroke = null;
         
        float origAlpha = 1.0f;
        Composite origComposite = ((Graphics2D)g).getComposite();
        if (origComposite instanceof AlphaComposite) {
            AlphaComposite origAlphaComposite = 
                (AlphaComposite)origComposite;
            if (origAlphaComposite.getRule() == AlphaComposite.SRC_OVER) {
                origAlpha = origAlphaComposite.getAlpha();
            }
        }
        
	    AffineTransform defaultTransform_ = g.getTransform();
// 
g.setComposite(AlphaComposite.getInstance(3, 1.0f * origAlpha));
AffineTransform defaultTransform__0 = g.getTransform();
g.transform(new AffineTransform(1.0f, 0.0f, 0.0f, 1.0f, -0.0f, -0.0f));
// _0
g.setComposite(AlphaComposite.getInstance(3, 1.0f * origAlpha));
AffineTransform defaultTransform__0_0 = g.getTransform();
g.transform(new AffineTransform(1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f));
// _0_0
g.setComposite(AlphaComposite.getInstance(3, 1.0f * origAlpha));
AffineTransform defaultTransform__0_0_0 = g.getTransform();
g.transform(new AffineTransform(1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f));
// _0_0_0
paint = new Color(139, 183, 240, 255);
shape = new GeneralPath();
((GeneralPath)shape).moveTo(40.0, 77.5);
((GeneralPath)shape).curveTo(19.322, 77.5, 2.5, 60.678, 2.5, 40.0);
((GeneralPath)shape).curveTo(2.5, 19.321999, 19.322, 2.5, 40.0, 2.5);
((GeneralPath)shape).curveTo(60.678, 2.5, 77.5, 19.322, 77.5, 40.0);
((GeneralPath)shape).curveTo(77.5, 60.678, 60.678, 77.5, 40.0, 77.5);
((GeneralPath)shape).closePath();
g.setPaint(paint);
g.fill(shape);
g.setTransform(defaultTransform__0_0_0);
g.setComposite(AlphaComposite.getInstance(3, 1.0f * origAlpha));
AffineTransform defaultTransform__0_0_1 = g.getTransform();
g.transform(new AffineTransform(1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f));
// _0_0_1
g.setComposite(AlphaComposite.getInstance(3, 1.0f * origAlpha));
AffineTransform defaultTransform__0_0_1_0 = g.getTransform();
g.transform(new AffineTransform(1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f));
// _0_0_1_0
paint = new Color(78, 122, 181, 255);
shape = new GeneralPath();
((GeneralPath)shape).moveTo(40.0, 3.0);
((GeneralPath)shape).curveTo(60.402, 3.0, 77.0, 19.598, 77.0, 40.0);
((GeneralPath)shape).curveTo(77.0, 60.402, 60.402, 77.0, 40.0, 77.0);
((GeneralPath)shape).curveTo(19.598, 77.0, 3.0, 60.402, 3.0, 40.0);
((GeneralPath)shape).curveTo(3.0, 19.598, 19.598, 3.0, 40.0, 3.0);
((GeneralPath)shape).moveTo(40.0, 2.0);
((GeneralPath)shape).curveTo(19.013, 2.0, 2.0, 19.013, 2.0, 40.0);
((GeneralPath)shape).curveTo(2.0, 60.987, 19.013, 78.0, 40.0, 78.0);
((GeneralPath)shape).curveTo(60.987, 78.0, 78.0, 60.987, 78.0, 40.0);
((GeneralPath)shape).curveTo(78.0, 19.013, 60.987, 2.0, 40.0, 2.0);
((GeneralPath)shape).lineTo(40.0, 2.0);
((GeneralPath)shape).closePath();
g.setPaint(paint);
g.fill(shape);
g.setTransform(defaultTransform__0_0_1_0);
g.setTransform(defaultTransform__0_0_1);
g.setTransform(defaultTransform__0_0);
g.setComposite(AlphaComposite.getInstance(3, 1.0f * origAlpha));
AffineTransform defaultTransform__0_1 = g.getTransform();
g.transform(new AffineTransform(1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f));
// _0_1
paint = new Color(255, 255, 255, 255);
shape = new Ellipse2D.Double(37.0, 21.0, 6.0, 6.0);
g.setPaint(paint);
g.fill(shape);
g.setTransform(defaultTransform__0_1);
g.setComposite(AlphaComposite.getInstance(3, 1.0f * origAlpha));
AffineTransform defaultTransform__0_2 = g.getTransform();
g.transform(new AffineTransform(1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f));
// _0_2
g.setComposite(AlphaComposite.getInstance(3, 1.0f * origAlpha));
AffineTransform defaultTransform__0_2_0 = g.getTransform();
g.transform(new AffineTransform(1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f));
// _0_2_0
paint = new Color(255, 255, 255, 255);
shape = new GeneralPath();
((GeneralPath)shape).moveTo(43.0, 56.0);
((GeneralPath)shape).lineTo(43.0, 31.0);
((GeneralPath)shape).lineTo(35.0, 31.0);
((GeneralPath)shape).lineTo(35.0, 33.0);
((GeneralPath)shape).lineTo(37.0, 33.0);
((GeneralPath)shape).lineTo(37.0, 56.0);
((GeneralPath)shape).lineTo(35.0, 56.0);
((GeneralPath)shape).lineTo(35.0, 58.0);
((GeneralPath)shape).lineTo(45.0, 58.0);
((GeneralPath)shape).lineTo(45.0, 56.0);
((GeneralPath)shape).closePath();
g.setPaint(paint);
g.fill(shape);
g.setTransform(defaultTransform__0_2_0);
g.setTransform(defaultTransform__0_2);
g.setTransform(defaultTransform__0);
g.setTransform(defaultTransform_);

	}

    /**
     * Returns the X of the bounding box of the original SVG image.
     * 
     * @return The X of the bounding box of the original SVG image.
     */
    public static double getOrigX() {
        return 2.0;
    }

    /**
     * Returns the Y of the bounding box of the original SVG image.
     * 
     * @return The Y of the bounding box of the original SVG image.
     */
    public static double getOrigY() {
        return 2.0;
    }

	/**
	 * Returns the width of the bounding box of the original SVG image.
	 * 
	 * @return The width of the bounding box of the original SVG image.
	 */
	public static double getOrigWidth() {
		return 76.0;
	}

	/**
	 * Returns the height of the bounding box of the original SVG image.
	 * 
	 * @return The height of the bounding box of the original SVG image.
	 */
	public static double getOrigHeight() {
		return 76.0;
	}

	/**
	 * The current width of this resizable icon.
	 */
	int width;

	/**
	 * The current height of this resizable icon.
	 */
	int height;

	/**
	 * Creates a new transcoded SVG image.
	 */
	public Info() {
        this.width = (int) getOrigWidth();
        this.height = (int) getOrigHeight();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see javax.swing.Icon#getIconHeight()
	 */
    @Override
	public int getIconHeight() {
		return height;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see javax.swing.Icon#getIconWidth()
	 */
    @Override
	public int getIconWidth() {
		return width;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.jvnet.flamingo.common.icon.ResizableIcon#setDimension(java.awt.Dimension
	 * )
	 */
	@Override
	public void setDimension(Dimension newDimension) {
		this.width = newDimension.width;
		this.height = newDimension.height;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see javax.swing.Icon#paintIcon(java.awt.Component, java.awt.Graphics,
	 * int, int)
	 */
    @Override
	public void paintIcon(Component c, Graphics g, int x, int y) {
		Graphics2D g2d = (Graphics2D) g.create();
		g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
				RenderingHints.VALUE_ANTIALIAS_ON);
		g2d.translate(x, y);

        double coef1 = (double) this.width / (double) getOrigWidth();
        double coef2 = (double) this.height / (double) getOrigHeight();
        double coef = Math.min(coef1, coef2);
        g2d.clipRect(0, 0, this.width, this.height);
        g2d.scale(coef, coef);
        g2d.translate(-getOrigX(), -getOrigY());
        if (coef1 != coef2) {
            if (coef1 < coef2) {
               int extraDy = (int) ((getOrigWidth() - getOrigHeight()) / 2.0);
               g2d.translate(0, extraDy);
            } else {
               int extraDx = (int) ((getOrigHeight() - getOrigWidth()) / 2.0);
               g2d.translate(extraDx, 0);
            }
        }
        paint(g2d);
        g2d.dispose();
	}
}

`

**Comment by kirill-grouchnikov** [comment]
This Java code was generated with the latest 5.2dev bits. Note that it's not enough to *run* it with 5.2. You also have to *generate* it with 5.2.

**Comment by plingsi** [comment]
Hi,
I've simply generated a lot of classes based on the SVG transcoder from this site:
http://ebourg.github.io/flamingo-svg-transcoder/
Do i have to regenerate them? Is there a better way?

Regards,
Erling

**Comment by kirill-grouchnikov** [comment]
I don't know what that site is, and how long ago it has forked Flamingo / Peacock sources.

I'm using SvgBatchConverter class which is part of Flamingo. The first parameter is the location of input folder with SVG files. This is also where the generated .java classes will be placed. The second parameter is the package name for all generated .java classes.

**Comment by plingsi** [comment]
I will try that - thank you!
Regards,
Erling

**Comment by IvanRF** [comment]
@kirill-grouchnikov I always have the doubt of why the SVG to Java conversion is needed. Would involve too much runtime processing to directly support SVG files as icons instead of Java transcoded files?

**Comment by kirill-grouchnikov** [comment]
The org.pushingpixels.flamingo.api.svg package already provides runtime support for SVG sources. It is using Batik for asynchronous loading / parsing of SVG content, and exposing it via the generic ResizableIcon interface. It also supports loading SVG content from zipped format.

The main downside is that you need to bring Apache Batik as the runtime dependency, and that's a significant addition to the overall binary size. Also, the initial parsing can be quite time-consuming, which means that your UI will not be rendered fully as one initial pass. Offline transcoding to Java2D-based classes takes care of that. However, the transcoding doesn't support the full SVG spec, specifically around textual content and embedded bitmaps.

The final thing here is that Apache Batik has seen quite a few releases since I've last worked on the transcoder / runtime. There might have been big performance improvements since then - specifically for the online mode. I don't have immediate plans to move to Batik 1.9 (from whichever version happened to be current ~6-7 years ago).

**Comment by IvanRF** [comment]
Oh, I remember now, yes Batik is a big library and at least in my case it would have no other purpose other than for icons. Yeap, I will continue with Java2D 😄 
BTW, it took a very long time to start seeing SVG files on the web. You were a precursor on this subject, I think I discovered SVG icons with Flamingo like 8 years ago 👍

**Comment by kirill-grouchnikov** [comment]
KDE 4 (circa 2007/8) was using SVG in a lot of places. Its source repository (Oxygen icons) was a big part of the Rainbow test app back then. See https://github.com/kirill-grouchnikov/rainbow/blob/master/src/org/pushingpixels/rainbow/RainbowSvnViewer.java

Those two repositories are long gone now, probably moved somewhere else.

**Comment by plingsi** [comment]
Tested all icons with 5.2 - it's working.
