### ISSUE TITLE
Application menu cuts of secondary menu entries

### ISSUE THREAD

**Issue by matthiasblaesing** [kirill-grouchnikov/flamingo#13]
While primary entries in the Application menu cause it to grow, the same does not happen for secondary entries. To illustrate it, I added some "dummy" entries to the print menu of the "BasicCheckRibbon" test case. 

![auswahl_001](https://user-images.githubusercontent.com/2179736/30226438-448391e8-94d6-11e7-8ba0-993f636921b2.png)

I think the menu should either grow or a scrollbar should be automatically added.

**Comment by kirill-grouchnikov** [comment]
Should definitely kick in scrolling here.

**Comment by kirill-grouchnikov** [comment]
And also not close the application menu on mouse scroll (basically extend the fix for https://github.com/kirill-grouchnikov/flamingo/issues/3 into the application menu as well)

**Comment by matthiasblaesing** [comment]
Thank you - this looks good.
