### ISSUE TITLE
Tag for 5.2

### ISSUE THREAD

**Issue by mka848** [kirill-grouchnikov/flamingo#18]
Hi Kirill,

I cannot seem to find a 5.2 branch in source repo. 
Is it intentional or something that will be done later?

/Mikael

**Comment by kirill-grouchnikov** [comment]
I don't do branches. Everything is in the main trunk.

https://github.com/kirill-grouchnikov/flamingo/tree/master/drop/5.2.00 is the binaries for the 5.2.00 release.
