### ISSUE TITLE
Bring JRibbon into the modern world

### ISSUE THREAD

**Issue by kirill-grouchnikov** [kirill-grouchnikov/flamingo#19]
Flatten the lines and the gradients
Application menu button -> rectangle
Application menu -> backstage

This is planned for 2018.H2 / 6.0 release

**Comment by utybo** [comment]
Will the current office button of the ribbon stay as an option or will it be entirely replaced by the Office 2013+ style?

**Comment by kirill-grouchnikov** [comment]
It will all be new style

**Comment by kirill-grouchnikov** [comment]
As part of modernizing the look of the ribbon, I'm also tweaking the API surface of JRibbon and JRibbonBand to work with ribbon commands instead of directly with command buttons. The commits that went in in the last few days (https://github.com/kirill-grouchnikov/flamingo/commits/master) have not been tagged with this issue. 

Backstage APIs will work with commands as well, and there's probably going to be significant changes in those APIs to make them scale up to a wider variety of content that can be placed there.

**Comment by kirill-grouchnikov** [comment]
Will be tracked in kirill-grouchnikov/radiance#8

See http://www.pushing-pixels.org/2018/05/23/hello-radiance.html for context.
