### ISSUE TITLE
Hi-DPI / scaling support in all components

### ISSUE THREAD

**Issue by kirill-grouchnikov** [kirill-grouchnikov/flamingo#2]
There's a whole bunch of issues in a lot of Flamingo components when the runtime font sizes are large. [This](https://github.com/kirill-grouchnikov/substance/issues/13) is just one such example of relying on hard-coded sizes for preferred width and / or height.

While it's worth considering providing this support for all core look-and-feels, if that proves to be too much work, such support will only be provided in the Substance Flamingo plugin.

From a very cursory look, there's a bunch of hard-coded values for
1. Preferred icon sizes in all command button layout managers (ribbon, breadcrumb bar, command menus)
2. Button width for the gallery scroller
3. Color squares in the color selector popup
4. Buttons in ribbon task pane

In addition:
1. Ribbon task pane in collapsed state is represented by a button that is too wide
2. Rich tooltips can go beyond screen bounds

**Comment by plingsi** [comment]
Hi, any updates om this issue?

**Comment by kirill-grouchnikov** [comment]
So far the closest I can get to this setup is to explicitly bump up the default font size used by Substance, but I don't think that it's a correct recreation of it.

Would it be possible to create a small sample on your machine that creates a JFrame with a single JButton on it - under one of Substance's look and feels. Then, print out the following values:

SubstanceSizeUtils.getControlFontSize
SubstanceSizeUtils.getComponentFontSize(yourButton)

I think that under that 200% DPI setting the second value should be exactly twice that of the first one. If that's indeed so, then it'll give me a place to start from to scale the icons on command buttons.

**Comment by kirill-grouchnikov** [comment]
Playing with the system preference for display resolution on my Mac doesn't show any issues. I think it's scaling the entire UI after it's been drawn by the app, so everything scales up and down.

**Comment by plingsi** [comment]
Hi,
When I print these values I get the following results (200%):
Ctrl front size -> 24
Component font size -> 24

Regards,
Erling

Fra: Kirill Grouchnikov [mailto:notifications@github.com]
Sendt: torsdag 13. april 2017 22.37
Til: kirill-grouchnikov/flamingo <flamingo@noreply.github.com>
Kopi: Erling Fagerlie <erling@shiplog.no>; Comment <comment@noreply.github.com>
Emne: Re: [kirill-grouchnikov/flamingo] Hi-DPI / scaling support in all components (#2)


So far the closest I can get to this setup is to explicitly bump up the default font size used by Substance, but I don't think that it's a correct recreation of it.

Would it be possible to create a small sample on your machine that creates a JFrame with a single JButton on it - under one of Substance's look and feels. Then, print out the following values:

SubstanceSizeUtils.getControlFontSize
SubstanceSizeUtils.getComponentFontSize(yourButton)

I think that under that 200% DPI setting the second value should be exactly twice that of the first one. If that's indeed so, then it'll give me a place to start from to scale the icons on command buttons.

**Comment by kirill-grouchnikov** [comment]
The just uploaded 5.2-dev drop of Flamingo and 7.1-dev drops of Substance and Substance Flamingo should be the first major step towards high-DPI awareness of Flamingo components.

This is not fully done, as there are some hard-coded pixel values around. Will take a few more iterations, but in general this is ready for preliminary testing.

**Comment by plingsi** [comment]
Hi,
It looks much better – thanks!
Regards,
Erling Fagerlie

Fra: Kirill Grouchnikov [mailto:notifications@github.com]
Sendt: onsdag 19. april 2017 02.58
Til: kirill-grouchnikov/flamingo <flamingo@noreply.github.com>
Kopi: Erling Fagerlie <erling@shiplog.no>; Comment <comment@noreply.github.com>
Emne: Re: [kirill-grouchnikov/flamingo] Hi-DPI / scaling support in all components (#2)


The just uploaded 5.2-dev drop of Flamingo and 7.1-dev drops of Substance and Substance Flamingo should be the first major step towards high-DPI awareness of Flamingo components.

This is not fully done, as there are some hard-coded pixel values around. Will take a few more iterations, but in general this is ready for preliminary testing.

**Comment by kirill-grouchnikov** [comment]
Closing as of the latest drops of Flamingo and Substance Flamingo plugin. If you see anything not respecting high DPI mode, please file as separate issue(s).
