### ISSUE TITLE
RCP and RTL support 

### ISSUE THREAD

**Issue by am2222** [kirill-grouchnikov/flamingo#20]
Hi,
Does this component is usable in RCP applications?
Also Does it supports RTL languages?

**Comment by kirill-grouchnikov** [comment]
RTL - yes.
RCP - that depends on what you expect to be able to do. If you expect some sort of a visual editor where you can configure the various components in Eclipse, NetBeans or IntelliJ, then no.

**Comment by am2222** [comment]
@kirill-grouchnikov  thanks,in fact I want to use ribbon control in my java application which is based on RCP and have no idea if it has any conflicts or not

**Comment by kirill-grouchnikov** [comment]
This is a very vague and broad question. Flamingo is a set of Swing components. If you can use core components in that app, you can use Flamingo components. Beyond that it would be up to that particular RCP framework and how it supports custom third-party components.

**Comment by am2222** [comment]
@kirill-grouchnikov  thanks very much for your help
