### ISSUE TITLE
Can't mouse/trackpad scroll through items in JCommandPopupMenu

### ISSUE THREAD

**Issue by kirill-grouchnikov** [kirill-grouchnikov/flamingo#3]

**Comment by plingsi** [comment]
Hi,
Nice to see that Substance is updated again! Do you know when this error will be corrected?

Regards,
Erling Fagerlie

**Comment by kirill-grouchnikov** [comment]
This is in BasicPopupPanelUI.WindowTracker.eventDispatched method which hides all the popups. Will need to take a look what's happening for the command popup menu.

**Comment by kirill-grouchnikov** [comment]
I think it should hide all command popup menus when the source of the mouse wheel event is not in any of the Flamingo's command popup menu. 

So, in the scenario where you have a breadcrumb bar with an open and scrollable popup, mouse-wheeling within that popup scrolls up / down, and mouse-wheeling outside of the popup closes the popup and lets the underlying container handle that event. Fix coming soon.

**Comment by plingsi** [comment]
Hi,
I still have an issue with scrolling:
http://85.93.234.26/shiplog/Temp/error.png
Regards,
Erling

**Comment by kirill-grouchnikov** [comment]
This one looks different. Here the second-level menu doesn't kick in scrolling at all from what I can see. Is this just a simple JCommandPopupMenu with a bunch of menu buttons?

**Comment by plingsi** [comment]
Hi,
That is correct!
Regards,
Erling

Fra: Kirill Grouchnikov [mailto:notifications@github.com]
Sendt: onsdag 16. august 2017 14.01
Til: kirill-grouchnikov/flamingo <flamingo@noreply.github.com>
Kopi: Erling Fagerlie <erling@shiplog.no>; Comment <comment@noreply.github.com>
Emne: Re: [kirill-grouchnikov/flamingo] Can't mouse/trackpad scroll through items in JCommandPopupMenu (#3)


This one looks different. Here the second-level menu doesn't kick in scrolling at all from what I can see. Is this just a simple JCommandPopupMenu with a bunch of menu buttons?

**Comment by kirill-grouchnikov** [comment]
See the Javadocs of JCommandPopupMenu.setMaxVisibleMenuButtons. You would need to call it with some value that makes sense in the context of your particular content.

**Comment by plingsi** [comment]
Hi,
I’ve tried this – not working.
Regards,
Erling

Fra: Kirill Grouchnikov [mailto:notifications@github.com]
Sendt: onsdag 16. august 2017 14.13
Til: kirill-grouchnikov/flamingo <flamingo@noreply.github.com>
Kopi: Erling Fagerlie <erling@shiplog.no>; Comment <comment@noreply.github.com>
Emne: Re: [kirill-grouchnikov/flamingo] Can't mouse/trackpad scroll through items in JCommandPopupMenu (#3)


See the Javadocs of JCommandPopupMenu.setMaxVisibleMenuButtons. You would need to call it with some value that makes sense in the context of your particular content.

**Comment by kirill-grouchnikov** [comment]
TestCommandButtons in test.common package has the SCROLLABLE mode for populating popup content of command buttons. Works in that example.

<img width="319" alt="scrollable-popup" src="https://user-images.githubusercontent.com/52874/29582087-69f4727a-8749-11e7-87ae-04c89b67acfc.png">

**Comment by kirill-grouchnikov** [comment]
If this is not working for you, please file a separate issue with sample code that has one button and popup content that is configured to be scrollable with setMaxVisibleMenuButtons call.

**Comment by plingsi** [comment]
Hi,
I set max numbers to array size. My mistake. It is working now – thanks!

Regards,
Erling

Fra: Kirill Grouchnikov [mailto:notifications@github.com]
Sendt: tirsdag 22. august 2017 20.52
Til: kirill-grouchnikov/flamingo <flamingo@noreply.github.com>
Kopi: Erling Fagerlie <erling@shiplog.no>; Comment <comment@noreply.github.com>
Emne: Re: [kirill-grouchnikov/flamingo] Can't mouse/trackpad scroll through items in JCommandPopupMenu (#3)


TestCommandButtons in test.common package has the SCROLLABLE mode for populating popup content of command buttons. Works in that example.

[scrollable-popup]<https://user-images.githubusercontent.com/52874/29582087-69f4727a-8749-11e7-87ae-04c89b67acfc.png>
